int existe_arquivo(FILE*);
void cria_arq_obj();
void exclui_arq_obj();
void escreve_instrucao(TabelaDeInstrucoes* ,short int*);
void escreve_tabelas();
void escreve_tabela_uso();
void escreve_tabela_definicao();
void escreve_tabela_realoc();
void escreve_diretiva(char,short int);
void fecha_arq_obj();
