void verifica_linhas(FILE*);
int classifica(char*);
int existe_token(char* );
int existe_rotulo(char *);
int eh_numero(char );
int existe_instrucao(char *);
TabelaDeInstrucoes* busca_incrementa_posicao(char*);
int existe_diretiva(char *);
void busca_primeira_passagem(char*);
int existe_erro_conversao(long int numero, char*,char*,int);
